phoenix-rtos/phoenix-rtos-utils

psh/psh.c
1. Row size fixed to 80 characters (no line wrap).
2. More space for CMD column.
3. Added units conversions (base 2 and 10).
4. By default we show processes only (and their threads number in the THR column). In order to display threads separately pass -t option.
=> psh: ps display improvements

core/psh/ls.c
Major changes:
- `ls_readEntry()` - bug fixed
- `ls_readFile()` - bug fixed
- `ls_printLong()` - repeating `for`
- `psh_ls()` - `realloc()` with `NULL` pointer works as `malloc()`
In this version the `ls` command do not work if the argument is a directory.
=> ls.c: bugfixes and some code fixes

core/psh/psh.c
Fixed error if `exec` command has no arguments.
=> psh.c: fixed psh_exec()

core/psh/cat.c, core/psh/kill.c, core/psh/ls.c, core/psh/psh.c
- `psh_cat()` - fixed `fclose()` with `NULL` pointer
- `ps_kill()` - enough check `*end`
- `psh_ls_copyname()` - `realloc()` with `NULL' pointer works as `malloc()`
- `psh_ls_initbuffs()` and `psh_ls_expandbuf()` -  they are practically the same
- `psh_ls()` - fixed memory leak
- `psh.c` - removed trailing whitespaces
btw
Cast return value `malloc()` family functions is unnecessary and not recommended.
Error information should probably go to `stderr` and not `stdout`.
=> psh: fixed memory leak and some code changes

Makefile
TARGET=armv7m4-stm32l4x6
works ok, but
TARGET=armv7m4-stm32l4x6-myBoard
return an error – target not found.
This commit fixed it.
It's consistent with other repositories, eg. https://github.com/phoenix-rtos/phoenix-rtos-devices/blob/master/Makefile#L42
=> Fix Makefile for using TARGET with platform suffix

core/psh/Makefile, core/psh/psh.c
Added login feature. Can be turned on if psh is run under name "pshlogin" (symbolic link must be created in _targets like for some psh applets).
Checks user credentials against /etc/passwd.
Additional password may be specified by creating enviromental variable DEFUSR_PASSWD assigned with password hash value. Then additional credentials are:
username: defuser
password: <corresponding with given hash>
JIRA: BES-104
=> psh: login feature

core/psh/ls.c, core/psh/mkdir.c, core/psh/perf.c, core/psh/psh-empties.c, core/psh/top.c
Fix various minor coding style flaws, remove one redundant comment
and fix a printf format warning.
=> psh: Fix coding style

core/psh/Makefile, core/psh/psh.c, core/psh/sysexec.c
-added sysexec wildacrds. Allows execution only of predefined commands in /etc/wldcrds file (each command in newline)
or predefined in PSH_WILDCARDS enviroment variable (all comands in one line separated only by ';' sign)
If /etc/wldcrds file is not existing and no wildcards are specified in PSH_WILDCARDS then sysexec accepts all commands as usual
-removed #ifdef-s from psh login feature and assured that flags are defined in Makefile
JIRA: BES-148
=> psh: sysexec whitelist feature

core/psh/Makefile, core/psh/edit/edit.c
This change adds a plain text editor to the psh. The editor can be controlled with the `arrow keys`, `Insert`, `Delete`, `Home`, `End`, `Page Up`, `Page Down` keys, as well as with the keys listed on the bottom bar, under the status bar. The text editor window scales to the dimensions of the remote console (serial connections). The text editor has been tested on `imxrt1064` with `libtty` and `dummyfs`. But it does not work with `pc-tty` on `ia32` probably for the same reason as `vi` from `busybox`  ([issue #102](https://github.com/phoenix-rtos/phoenix-rtos-devices/issues/102))
See the attached short video showing the psh text editor on imxrt 1064.
https://user-images.githubusercontent.com/141153/119338115-e435ac00-bc8f-11eb-8db6-6503c7381b6a.mp4
JIRA: RTOS-23
=> psh: Add text editor

core/psh/sysexec/sysexec.c
- Sysexec whitelist can contain `*` wildcard.
- If command matches whitelist entry up to `*` it will be accepted (whatever follows).
- `*` must be specified as standalone argument
JIRA: BES-159
=> psh: sysexec whitelist support for `*` wildcard

core/psh/psh.c
I used `basename()` instead `splitname()`.
Using `splitname()`, you have to create a copy of `argv[0]` using `strdup()`.
=> psh: fixed separation of basename from argv[0]

core/psh/mount/mount.c
Conforms to libphoenix mount() implementation
Fixed also return code but it's not usable because of https://github.com/phoenix-rtos/phoenix-rtos-utils/issues/58.
=> psh: mount: make 5th parameter optional

core/psh/edit/edit.c
This fixes the case where memory is not freed if the only one available (the last one) row is deleted when a single (the last one)
character is removed.
JIRA: RTOS-33
=> psh/edit: fix mem leak

core/psh/exec/exec.c, core/psh/pshapp/pshapp.c, core/psh/runfile/runfile.c
Child processes should inherit PSH environment (especially PWD).
JIRA: RTOS-36
=> psh: fix exec environment resetting

core/psh/ps/ps.c
Rationale: 
- we have `top` for watching the CPU usage.
- `ps` sorts by PID in BSD and Linux by default so user expects that
JIRA: RTOS-35
=> psh: ps: sort by PID by default

core/psh/Makefile
JIRA: BES-167
Linker flag `stack-size` added to psh Makefile to increase its stack size on no MMU targets
Psh is very important Phoenix-RTOS program and as a user input/output program should have bigger stack than default one.
Also fixes the bug that cashes the imxrt1064 when `ls -l` is executed in psh.
=> psh: stack size change

core/psh/mem/mem.c
JIRA: ISC-118
On some platform psh/mem.c generates warning while build.
> format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'id_t' {aka 'unsigned int'} [-Wformat=]
Basing on example CI build https://github.com/phoenix-rtos/phoenix-rtos-utils/actions/runs/978986094 it affects all armv7m platfotm
 
Fixes #68
=> psh/mem: Fix warning message

core/psd/imx6ull/flashmng.c
JIRA: RTOS-67
Allocate bad blocks array on the heap.
Bad blocks array was probably overflowing stack on imx6ull.
=> psd: bad blocks array fix

core/psh/pshapp/pshapp.c, core/psh/sysexec/sysexec.c
JIRA: BES-170
- added break after sending SIGTTIN in `pshapp`
- sysexec regains control over terminal
Psh was left hanging after second execution both from `ash` and on imxrt106x using sysexec.
https://github.com/phoenix-rtos/phoenix-rtos-utils/issues/47
=> psh: fix hanging after second execution

core/psh/Makefile, core/psh/psh.c, core/psh/pshapp/auth.c, core/psh/pshapp/pshapp.c
Changes remove ambiguity between well known `login` command in UN*X like systems and current implementation of `login` applet in psh.
- `login` applet renamed to `auth` and moved to pshapp directory
- `pshlogin` moved to separate directory to allow execution, testing and excluding from building
-  trying to start second interactive psh (`pshapp`) under one psh process returns a message (either called from `psh` or `pshlogin` command)
JIRA: BES-164
=> psh: remove `login` applet ambiguity

core/psh/pshapp/pshapp.c
stop-gap for phoenix-rtos/phoenix-rtos-project#134
Introduces new warnings in compilation.
Removes some functionality.
Makes `psh` not to break when somebody presses `TAB`
=> psh: temporairly disable TAB-completion

core/psd/imx6ull/bcb.c, core/psd/imx6ull/bcb.h, core/psd/imx6ull/flashmng.c, core/psd/imx6ull/flashmng.h, core/psd/imx6ull/psd.c
- use direct FDs instead of buffered FILE*
- obtain NAND flash params dynamically
- generate FCB based on obtained NAND params
- remove obsolete chip functions (use /dev/flash0 file directly)
- fix badblock detection and management
- unionize flashmng interface
- remove unnecessary mmaped memory
- describe FUSEs blown
JIRA: DTR-88
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/121
=> imx6ull-psd: rewrite

core/psh/pshapp/pshapp.c
JIRA: PD-160
Change stopgap of psh autocompletion so it does not produce warnings. Commit valid till https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/78 will be merge
Psh produces warnings as there is a stopgap for psh autocompletion feature
=> psh: change stop-gap so it does not produce warnings

core/psd/imx6ull/psd.c
The last packet received with sdp_recv() can have size equal to HID_REPORT_2_SIZE - 1 (1024 bytes), which currently causes psd to wait for another packet if we haven't filled up full flash page yet. Use file size comparison for last packet detection.
psd hangs if last packet size equals to 1024 and we haven't filled up full flash page.
[JIRA: RTOS-70](https://jira.phoenix-rtos.com/browse/RTOS-70)
=> psd: fix data transfer condition in psd_writeFile()

core/psd/imx6ull/bcb.c
Changed FCB configuration forcing BootROM to use badblock markers instead of DBBT.
If firmware happens to lie on a badblock, BootROM will try load it from the next block.
[JIRA: DTR-95](https://jira.phoenix-rtos.com/browse/DTR-95)
=> psd: force BootROM to not use DBBT and check for badblock markers instead

core/psh/ls/ls.c, core/psh/pshapp/pshapp.c
Changed `lstat()` usage to `stat()` in ls and TAB autocompletion. `lstat()` doesn't resolve symlinks.
phoenix-rtos/phoenix-rtos-project#180
[JIRA: RTOS-86](https://jira.phoenix-rtos.com/browse/RTOS-86)
=> psh: fix ls and TAB autocompletion not resolving directory symlinks - use stat() instead of lstat()

core/psh/psh.c, core/psh/psh.h, core/psh/pshapp/auth.c, core/psh/pshapp/pshapp.c, core/psh/reboot/reboot.c, core/psh/uptime/uptime.c
This PR changes two things:
- removes `isrunpsh` logic
-  psh determines its interactivity by checking `cmdhist` pointer initialization
- makes `psh` return execution status in following manner:
- psh returns `0` if no error occured
- psh returns `1` and sets `errno` if error occured
Also i checked through return codes of some psh applets and unify their error return value to be negative as to conform with logic:
- inside psh negative value means error, 0 means success
- outside psh 1 means error, 0 means success
As for now psh returns `EOK` (`0`) no matter what happens during its execution. This together with `isrunpsh` made it quite hard to get any information about psh execution. By getting rid of `isrunpsh` variable `psh` relies now only on important pointer `cmdhist` initialization …
=> psh: return codes and isrunpsh logic fix

core/psh/uptime/uptime.c
JIRA: RTOS-108
Make uptime return by default more human readable information like
```
up 1024 days and 23:59:59
```
, instead of just displaying only the seconds since booting up.
=> psh: make uptime more human readable

core/psh/reboot/reboot.c
Currently implemented only for imx6ull - booting from secondary NAND
image.
JIRA: DTR-181
=> psh: reenable option to target-specific reboot operation

core/nandtool/flashmng.c, core/nandtool/flashmng.h, core/nandtool/nandtool.c
- fix exit code on success 
- fix negative exit codes
- nandwrite: make possible to use non-absolute device paths (needed for device symlinks to work)
- better logging in non-interactive run
- add option to write jffs2 cleanmarkers 
(WARN: not useable on imx6ull right now due to bug in write() when meta
on flash is non-empty)
DTR-181
=> Nandwrite enhancements

core/psh/hm/hm.c
Wrong error msg is produced if hm encounters EINTR during wait()
=> psh/hm: Fixed EINTR not being handled on wait()

core/psh/ls/ls.c
- handle calling ls with -d option without additional arguments
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/190
=> psh: ls: fix calling -d without specified directory

core/psh/pshapp/pshapp.c
JIRA: CI-99
- psh: apply clang-format to pshapp.c
- psh: history: print help message when wrong arguments are passed
before change:
after change:
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/250
=> psh: history: print help message when wrong arguments are passed

psh/mem/mem.c
JIRA: PD-217
Add handling `page.mapsz` with negative value (means page map hasn't been initialized and -p option for `mem` command isn't available)
Related to:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/281
When 
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/281 
is merged, calling `mem -p` on non-mmu targets will print blank line. With this change there will be the proper statement.
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/281
=> psh: mem: add statement about unavailable page view on non-mmu targets

psh/runfile/runfile.c, psh/touch/touch.c
Two fixes for psh applets:
- `runfile`: add error message if error comes from `waitpid()`
- `touch`: prepared this command for `utimes()` full implementation
- `runfile` changes:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/248
- `waitpid()` error message should be visible if it comes from _before_ the execution and after context switch
- `touch` changes:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/252
- `touch` currently crashes system if called on binary file and truncates files to zero length if file was present before. 
- Proposed changes make `touch` prepared for working `utimes()` implementation as currently:
- `utimes()` uses stub syscall just to satisfy busybox ([code permalink](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/3b85faa3db0c …
=> Fixes for `runfile` and `touch`

psh/touch/touch.c
JIRA: PD-214
fix for https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/112
Uncatched error (due to not testing touch due to not working touch etc.) of buffer overflow in `utimes()` usage
=> touch: utimes buffer fix

psh/Makefile, psh/echo/echo.c, psh/psh.c, psh/psh.h, psh/pshapp/pshapp.c, psh/runfile/runfile.c, psh/sysexec/sysexec.c
JIRA: RTOS-156
We want to be able to get exit status of app/applet in psh.
Also somewhat fixed waitpid usage (EINTR and other errors handling)
I had no idea how to call new exit status getter applet, so I just implemented echo command along with simulated $? variable
=> Added exit status and echo command

psh/cat/cat.c
JIRA: RTOS-160
Cat returned negative values, also did not return error on file opening.
Also made cat more MISRA friendly. Not really sure about getopt loop, I'm open for sugestions
Fix for https://github.com/phoenix-rtos/phoenix-rtos-project/issues/336
=> psh/cat: Fixed cat's return value

psh/ls/ls.c
- handle printing files with names longer than window size
- disable reset attributes esc sequence, where it's not necessarily
JIRA: RTOS-165
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/347
- before change:
- after change:
=> psh: ls: fix printing files longer than window size

psh/Makefile, psh/date/date.c
DONE: PD-249
Add simple date command
- I wanted to put 'Test Driven Developement' to work, so I trained on developement of simple psh applet `date`. 
- This applet was developed alongside with tests which are in separate PR:
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/98
- Documentation PR:
- https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/110
=> psh: add `date` applet

psh/mkdir/mkdir.c
- psh: mkdir: handle name too long error
JIRA: PD-270
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/393
=> psh: mkdir: handle errno returned by mkdir() function

_targets/Makefile.armv7m7-imxrt106x, meterfs-migrate/Makefile, meterfs-migrate/migrate.c
JIRA: BES-202
Tool that converts meterfs from verion before 095ba8a00f10c3b41a9258bb737ebac4d62f25e3 to be compatible with new metadata structures.
Need to convert existing meterfs partition without losing data.
=> Added meterfs-migrate tool

psh/Makefile
JIRA: BES-209
This change allows adding project-specific applets and link them together with their dependencies to `psh`. It requires however relinking `psh` from the project build script. For example:
```
b_log "Relinking psh"
make -C "phoenix-rtos-utils" psh install PSH_PROJECT_DEPS="upgrade libz"
```
=> Makefile: Allow linking external project-specific applets

psh/pshapp/pshapp.c
JIRA: RTOS-232
Previously, it was only possible to run programs with an absolute path starting with `/`, this change introduces
the ability to run also using a relative path, e.g. relative to working directory.
It is expected that executable path begins with: `/`, `./` or `../` (pre-checked in `pshapp.c` - this change)
Allowed paths are (depending on current working direcory, eg. after changing it with `cd /usr/bin`):
```bash
/usr/bin/hello
./hello
../bin/hello
../../../../../usr/bin/hello
./././hello
```
Full path is then checked by `runfile.c:` `execv()`->`resolve_path()`
=> pshapp: Allow execute both absolute and relative paths

psh/mem/mem.c, psh/mkdir/mkdir.c, psh/pshapp/pshapp.c, psh/touch/touch.c
- psh: fix mem return codes
- psh: fix touch return codes
- psh: fix mkdir return codes
- psh: fix applets return codes in pshapp.c
- EOK is not cross-platform
- Sometimes 0 was returned even if error had been occurred
- Errno shall not be returned as exit status
=> psh: fix return codes for history, mkdir, touch and mem

psh/pshapp/pshapp.c
- psh: reset getopt by setting optind to 0 not 1
- It's necessary to properly reset getopt function (requires the change mentioned below). 9ed7c715d3e97f3112e3cbb30920171cf64163fa libphoenix
- JIRA: RTOS-271
=> psh: reset getopt by setting optind to 0 not 1

nandtool/flashmng.c, nandtool/flashmng.h, nandtool/nandtool.c
JIRA: DTR-351
This change allows dumping either raw or normal blocks to an output file. An example command used to dump 3 blocks of data including OOB data:
`nandtool -d 476:3 -o dump.bin -b /dev/mtd0p6`
This change is needed for debugging reasons.
=> nandtool: Add dumping functionality

psh/psh.c, psh/psh.h, psh/pshapp/pshapp.c
psh: set return code for unknown command case
Fixes: phoenix-rtos/phoenix-rtos-project#493
DONE: RTOS-285
=> psh: set return code for unknown command case

psh/pshapp/pshapp.c
=> psh: Fix prompt eating last line if no \n was present

psh/Makefile, psh/psh.c, psh/psh.h, psh/pshapp/pshapp.c, psh/tty/tty.c
This change introduces the `tty` command which allow to change the current working terminal device or print tty device name (a path) to which `psh` standard I/O is currently connected.
The `tty` command is protected against using the wrong `tty` device and so that for example on`ia32` one does not mistakenly redirect the output to the hard disk `/dev/hda`:
**Example work flow** 
(two tty devices primary `/dev/console` alias `/dev/uart11`, and auxiliary`/dev/uart12`):
On `/dev/console` (print current connected tty device):
```
(psh)% tty
/dev/console
(psh)% _
```
On `/dev/console` (change to aux uart port `/dev/uart12`):
```
(psh)% tty /dev/uart12
Changing psh tty device '/dev/console' to '/dev/uart12'
_
```
Console prompt moved to `/dev/uart12`, to verify print `tty` device name:
``` …
```
=> psh: Add `tty` command

psh/edit/edit.c
Cursor position and attributes are saved with `ESC 7` and restored with `ESC 8`, color and text attribute reset `ESC [ 0 m` must be done right after restoring the cursor context to take effect, otherwise the then saved context is restored will overwrite what we reset with the restored cursor context, easy.
This change is connected with https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/350 pull-request, but may be merged independently.
JIRA: RTOS-378
=> edit: fix attribute reset after cursor pos restore

psh/Makefile, psh/ln/ln.c
Extends the `psh` command set with (`ln` command) the ability to make links between files and directories. Supported are symbolic and hard links.
JIRA: RTOS-409
=> psh: Implement `ln` command

cm4-tool/tool.c
quickfix: Allow values for parameters (e.g. offset/address for vector table) to be specified as decimal or hexadecimal value.
JIRA: RTOS-457
=> Allow either `dec` or `hex` values for parameters in cm4-tool

psh/Makefile, psh/rm/rm.c, psh/rmdir/rmdir.c
Adds basic, non-recursive implementations of:
* `rm`  -  unlink files and `rm -d` remove directories
* `rmdir` - remove directories.
Both commands intentionally does not support wildcards.
JIRA: RTOS-517
=> psh: Implement `rm` and `rmdir` commands

_targets/Makefile.armv7m7-imxrt106x
This change removes `psd` from `DEFAULT_COMPONENTS` for `armv7m7-imxrt105x` target, because psd is not supported on this platform.
JIRA: RTOS-575
=> makes: remove unsupported psd on imxrt105x

psh/ping/ping.c, psh/psh.h
Filter incoming ICPM messages:
- by type (parse only ECHOREPLY) - fixes `ping 127.0.0.1`
- by ID - fixes concurrent pings
Fixes: phoenix-rtos/phoenix-rtos-project#826
=> psh/ping: fix filtering correct reply packet

psh/pshapp/pshapp.c
JIRA: RTOS-625
Previously there was a timeframe in which entered command could be duplicated by echo of tty console in cannonical mode leading to issues in CI.
=> psh: printf prompt after entering raw mode

psh/dmesg/dmesg.c, psh/edit/edit.c, psh/nc/nc.c, psh/psh.c, psh/psh.h, psh/pshapp/pshapp.c
The `reset` command in the `psh` console is used to restore the settings of the terminal (to cooked, non-raw mode) after some program terminates abnormally leaving e.g. hidden text cursor or termios in raw mode.  The reset command works by performing the following operations:
* clear the screen,
* restore cursor mode and terminal settings 
The `clear` command clears the screen without clearing the scrollback buffer (works like `CTRL+L`, but may be called from psh script).
These commands are internal (builtin commands) to pshapp command interpreter (commands should not be in `/bin` path).
In real environment (big targets), `reset` is implemented by [`tset`](https://man.openbsd.org/reset) which is a dedicated terminal settings management tool.
Additionally `write()` function is being …
=> psh: implement command to `reset` terminal

psh/dd/dd.c
Statistics `records in and out` coount was printed to stdout instead of stderr.
This PR fixes that.
=> psh/dd: fix printing statistics to stderr

psh/pshapp/pshapp.c
DONE: RTOS-645
Hopefully fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/746
=> psh: Increase sleep on start to allow dmesg to finish

psh/ls/ls.c
`ls -l` command now prints the modification year of the file if the year is different from the current year. 
Before:
```sh
(psh)% date
Thu, 01 Jan 70 00:00:02
(psh)% ls -l
[...]
drwxrwxr-x  6 ---  ---   1024 Sep 18 11:59 usr
drwxrwxr-x  3 ---  ---   1024 Jan  1 00:00 var
```
After:
```sh
(psh)% date
Thu, 01 Jan 70 00:00:02
(psh)% ls -la
[...]
drwxrwxr-x  6 --- ---   1024 Sep 18  2023 usr
drwxrwxr-x  3 --- ---   1024 Jan  1 00:00 var
```
This behavior is consistent with other implementations of `ls`, for example in Bash.
Fixes issue https://github.com/phoenix-rtos/phoenix-rtos-project/issues/552
Some scripts (in particular tests) assume that the command always prints modification time.
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/260 needs to be merged first in order for tests …
=> psh: print year in `ls -l` command if different from current

psh/pshapp/pshapp.c
In function `psh_completepath` directory handle was not closed after listing the directory. This led to a resource leak every time the path completion feature was used. This PR fixes the resource leak.
=> psh: close directory after listing

psh/Makefile, psh/printenv/printenv.c, psh/pshapp/env.c, psh/pshapp/pshapp.c
Proof that change works correctly  on GH (updated project):
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/930
The change introduces commands for handling environment variables in psh both on the command line and in the initialization script. The commands are:
* `export` - (builtin)  set and propagate variable names (list) to process environment
* `unset` -  (builtin) removes variable names (list) from environment
* `printenv` - prints all environment variables or selected ones (list).
with this PR it is possible to use `export PATH` in [`rc.psh`](https://github.com/phoenix-rtos/phoenix-rtos-project/blob/c1a93f876635749125ef5fde4a4f41f08af5d3f8/_projects/ia32-generic-qemu/rootfs-overlay/etc/rc.psh) init script:
```bash
:{}:
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export …
```
=> psh: add support for environment variables in psh script

psh/ifconfig/ifconfig.c
`interfaceFlags` is of type `unsigned int` (good for maintaining IPv6 compatibility with `ifr_flags6`), but currently `ifr_flags` in ipv4 is used, which is of type `short`. When assigning the `IFF_DYNAMIC=0x8000` flag, the sign is expanded to an integer (0xffff8000), which, if used as an upper limit in a loop shifting left through bits of the `interfaceFlags` variable, causes undefined behavior in the loop condition, which results in overflow in the loop, which `leads to its infinite iteration`.
JIRA: RTOS-695
=> psh: fix ifconfig ub in interface print flags

psh/ifconfig/ifconfig.c
It is possible to invoke a `dynamic address` on network interface using `LwIP's built-in DHCP client` by setting the `IFF_DYNAMIC` flag. Accordingly, setting or clearing this flag on the interface supporting this property (e.g. `ethernet`) activates or deactivates the DHCP client.
Activating and deactivating dhcp:
JIRA: RTOS-696
Automatic address assignment in qemu (with its DHCP server).
=> psh/ifconfig: add trigger to activate dhcp client

nandtool/flashmng.c, nandtool/flashmng.h, nandtool/nandtool.c, psd/imx6ull/bcb.c, psd/imx6ull/psd.c, psd/imxrt/psd.c, psh/ls/ls.c, psh/mem/mem.c
Adapt includes and types to changes in https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/518
=> cleanup headers

psh/kill/kill.c
The commit with the title "WIP" will be removed, its purpose is to point out differences from the CI unit test.
The purpose of this change is to implement the `kill` command to accept a POSIX-compliant signal number or signal name, which then can be sent to one or more processes.
The  `default` `signal` for kill is `TERM`.
```
Usage: kill [-s signal | -signal] <pid [...]>
```
send the default `TERM` signal to pids 14 15 20
`(psh)% kill 14 15 20`
Send a KILL signal (this was the behavior of the previous implementation of psh kill command)
`(psh)% kill -SIGKILL 10`
or
`(psh)% kill -KILL 10`
or
`(psh)% kill -9 10`
Some other examples
`(psh)% kill -SIGHUP 8`
`(psh)% kill -s SIGQUIT 9 10 11`
Sending signals to processes like `SIGUSR1`, `SIGQUIT`, `SIGHUP`.. not just single `signal_kill`.
JIRA: …
=> psh: reimplement 'kill' command

psh/Makefile, psh/chmod/chmod.c
pSH'ell `chmod` command provides ability to change file(s) mode bits through `chmod()` in a `P1003.2 4.7.7` conformant way.
Each `mode` is either in octal form like e.g. `0775` or symbolic form e.g. `a-rwx,a+Xr,ug+w`.
usage example:
(psh)% `chmod a-rwx,a+xr,ug+w /etc/rc.psh`
(psh)% `chmod 0775 /etc/rc.psh`
(psh)% `chmod -R 0775 /usr/bin /bin /sbin`
=> psh: Add `chmod` command

psh/Makefile, psh/hd/hd.c, psh/psh.c, psh/psh.h
The `hd` tool introduced in this PR is used to dump the contents of files and read devices (if read is supported by driver) in the form of `hexdump`, quick examples of use are provided below.
```
(psh)% hd -h
Usage: hd -s offset -n length [filename]
```
text-file:
```
(psh)% hd /etc/platform 
00000000  69 61 33 32 0a                                    |ia32.|
00000005
```
32bytes of MBR:
```
(psh)% hd -n 32 /dev/hda
00000000  ea 05 7c 00 00 fa 31 c0  8e d8 8e c0 8e d0 bc 00  |..|...1.........|
00000010  70 fb 88 16 4f 7d bb aa  55 b4 41 cd 13 72 16 81  |p...O}..U.A..r..|
00000020
```
rand():
```
(psh)% hd -n 34 /dev/urandom
00000000  33 ac da 00 5e f8 d5 78  e6 f8 fc 58 a6 d1 89 06  |3...^..x...X....|
00000010  c3 c4 a2 53 a8 46 34 49  db 1c 4b 06 60 80 a7 6c  |...S.F4I..K.`..l|
00000020 …
```
=> psh/hd: Introduce hexdump utility

psh/mem/mem.c
`mem -s` command in psh now prints the map name, using the recently introduced feature in `meminfo` syscall.
=> psh/mem: print shared map name

psh/psh.c, psh/pshapp/auth.c, psh/pshapp/pshapp.c
solves pbrolem with run psh on the same device as authentication
JIRA: RTOS-996
=> psh: fix pshlogin on custom device
