core/psh/Makefile, core/psh/psh.c, core/psh/psh.h, core/psh/top.c, core/psh/top.h
Temporarily put some common declarations to new header psh.h.
Some code fragments in top.c are taken with slight modification from psh_ps(). In the future, some of it should be common.
=> psh: Add top utility

core/psh/psh.c
Commands sorted.
My suggestion, let the author correct the code indentation in `top.c`
=> psh.c: added top command to help

core/psh/psh.c
In the current version when an error occurs, the terminal is not reset to its original settings.
Since jumping should be avoided, I suggest this solution.
=> psh: fixed restore oryginal terminal settings

core/psh/ping.c
There is still one warning triggered on ia32. Last fixes also introduced one error, when receiving ping msg.
=> psh/ping: Fix warning on ia32

core/psh/help/help.c, core/psh/psh.c, core/psh/psh.h, core/psh/pshapp/pshapp.c
- applets register alphabetically
- changed applets list interface
- changed alignment in help
- fixed "history not initialized" bug
- flag check in pshlogin corrected
JIRA: PD-74
=> Psh: applets fixes after modularization

core/psh/Makefile, core/psh/nslookup/nslookup.c
=> psh: Add nslookup command

core/psd/common/sdp.h, core/psd/imx6ull/flashmng.c, core/psd/imx6ull/flashmng.h, core/psd/imx6ull/psd.c
=> imx6ull-psd: implement single partition erase

core/psd/imx6ull/bch.c
=> psd: imx6ull: fix memory leak in error condition in bch

core/psh/ls/ls.c
=> psh: ls: fix date printing

core/psh/ping/ping.c
Reformat code to conform to clang format and improve timeout handling.
I came across the issue with timeout handling, when testing the Huawei LTE modem. In the old version, after returning from `recvfrom()` due to a timeout error, a next call would immediately return after having received the delayed packet. It caused the time calculation to break. In the new version, we exit the command after the first timeout, which is a much simpler solution and makes the meaning of `-W` (timeout) parameter more obvious. 
Moreover, I decided to increase the deafult timeout value, as the ping delay on Huawei modem quite often exceeds 500 ms.
=> psh/ping: Code cleanup and minor code improvements

core/psd/imx6ull/flashmng.c
=> psd: bad blocks pointer fix (broken by previous commit)

core/psd/imx6ull/flashmng.c
=> psd: flashmng_checkRange() return value fix

core/psh/sysexec/sysexec.c
A change to both `sysexec` (psh) command and `proc_syspageSpawnName()` which allows to run syspage programs with the default memory map (dmap) set in plo using the app command.
JIRA: RTOS-74
It is a pain to keep typing the default map to `sysexec`  command for an application when it is given in the `app` command, so this needs be changed.
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/39
https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/12
=> psh: allow sysexec to spawn programs with default map

core/psh/Makefile, core/psh/uptime/uptime.c
=> psh: add uptime

core/psd/imx6ull/bcb.c
Fixed writing FCB and DBBT data to flash:
- DBBT entries weren't saved at all (bad !err check),
- FCB copies weren't saved to next blocks (next pages),
- removed unnecessary malloc() in dbbt_flash(),
[JIRA: DTR-120](https://jira.phoenix-rtos.com/browse/DTR-120)
=> psd: fix writing FCB and DBBT

core/psh/pshapp/pshapp.c
JIRA: PD-160
Autocompletion using `tab` is brought back after being disabled as quick-fix (725427d6496c07f7ed8f906c59a831970e5cd267)
Using autocompletion is a valid tool when using system without any _select_ tool. This commit changes the way `psh` autocompletes the line if partially filled with correct directory/file name.
Main issue:
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/134
- https://github.com/phoenix-rtos/libphoenix/pull/117
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/40).
=> psh: tab autocompleting fix

core/psd/imx6ull/psd.c
As the title says.
Needs https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/234 for working syscall.
=> psd: imx6ull: add watchdog fuse and kick

_targets/Makefile.armv7a7-imx6ull, _targets/Makefile.armv7m3-stm32l152xd, _targets/Makefile.armv7m4-stm32l4x6, _targets/Makefile.armv7m7-imxrt106x, _targets/Makefile.armv7m7-imxrt117x, _targets/Makefile.ia32-generic, _targets/Makefile.riscv64-spike, _targets/Makefile.riscv64-virt, core/healthmon/Makefile, core/healthmon/healthmon.c
Spawn processes and keeps them alive (by respawning them it they're ended/killed)
psh can end both normally and abnormally. It's needed for access to the device, so psh being killed is not an option. This tool can keep psh always available.
=> Simple Health Monitor

core/psh/reboot/reboot.c
JIRA: DTR-181
https://github.com/phoenix-rtos/libphoenix/pull/148
=> psh: reboot: add reboot reason retrieval

core/psh/runfile/runfile.c
JIRA: PD-213
In `psh` applet `runfile` early return was removed, and error handling was centralized at the end of the applet
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/248
This PR solves half of the issue mentioned above. It solves the `psh` hang-up after _runfile_-ing a directory as this scenario does not give back control over terminal to `psh` after `vfork()` error is raised. Proposed changes remove a possibility for early return if `vfork()` error was raised. Early return here can end in a situation where:
- child has taken control over terminal
- child failed, thus returns to parent
- parent executes `return -1` without getting back control over terminal, which here renders previously foreground running `psh` a background running `psh`
=> psh: runfile: remove early return when `vfork()` fails

core/psh/Makefile, core/psh/dmesg/dmesg.c, core/psh/psh.c, core/psh/psh.h, core/psh/pshapp/auth.c, core/psh/pshapp/pshapp.c
=> Handle kernel log buffer

psh/pm/pm.c
=> hm: add new options to monitor processes

psh/Makefile
=> pm: add to PSH_ALLCOMMANDS

psh/Makefile, psh/df/df.c
Added basic `df` command implementation.
[JIRA: DTR-100](https://jira.phoenix-rtos.com/browse/DTR-100)
=> psh/df: add basic implementation (based on busybox)

psh/ps/ps.c, psh/top/top.c
Fixed `ps` output formatting.
[JIRA: RTOS-166](https://jira.phoenix-rtos.com/browse/RTOS-166)
=> psh/ps/top: fix WAIT column formatting + add more space for PID and PPID columns

psh/ps/ps.c
Fixed `ps` command `TIME` calculation and formatting (see [opengroup](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ps.html)).
[JIRA: RTOS-172](https://jira.phoenix-rtos.com/browse/RTOS-172)
=> psh/ps: fix TIME column cumulative CPU time calculation and formatting

psh/mem/mem.c
JIRA: ISC-163
Adapted to changes in kernel's meminfo interface. 
Currently there is a problem with estimation of allocated/available memory on NOMMU targets. Shared maps parameters provide adequate information about total system memory.
=> psh/mem: Added option to print shared maps info. Added basic help

psd/imx6ull/flashmng.c
Size should not be equal PAGE_SIZE but the size of cleanmarkers.
DTR-102
=> psd/imx6ull: change size of meta data

nandtool/flashmng.c
Size should not be equal PAGE_SIZE but the size of cleanmarkers.
DTR-102
=> nandtool: change size of meta data flashmng_cleanMarkers

meterfs-migrate/migrate.c
Make it compatible with real fwrite
JIRA: BES-202
=> meterfs-migrate: Add fseek at the end of fwrite_workaround

psh/echo/echo.c
DONE: RTOS-191
Adds fake > and >> stream redirection to echo. Allows for easy writing stuff to files. 
Quite useful, albeit hacky implementation
=> psh/echo: Added fake stream redirections (> and >>)

psh/Makefile, psh/wget/wget.c
=> psh: Add wget applet

psh/Makefile, psh/ntpclient/ntpclient.c
Add tool to set system date using remote host via SNTP protocol.
JIRA: RTOS-197
https://user-images.githubusercontent.com/141153/177180977-77fca47b-0636-407f-905d-ad1880bdb936.mp4
=> psh: Add ntpclient applet

psh/cp/cp.c
JIRA: RTOS-227
Fix missing break per @kemonats suggestion
=> psh/cp: Add missing break

psh/cp/cp.c
JIRA: RTOS-229
Fix after adding of missing perror implementation
=> psh/cp: Use perror

psh/Makefile, psh/cd/cd.c, psh/pwd/pwd.c
JIRA: RTOS-228
Adds the ability to change the current working directory.
- imxrt1176-evk, stm32l4a6-nucleo (with `dummyfs` and `mkdir`, `ls`, `edit`, `touch`, `cat`, `cp`),
- ia32-generic (with `pc-ata/ext2` and `mkdir`, `ls`, `touch`, `cat`, `cp`).
- https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/126
- https://github.com/phoenix-rtos/phoenix-rtos-doc/pull/127
=> psh: Add `cd` and `pwd` commands

_targets/Makefile.armv7a7-imx6ull, metacheck/Makefile, metacheck/bch.c, metacheck/bch.h, metacheck/main.c
=> metacheck: Add utility for checking validity of metadata on imx6ull

psh/runfile/runfile.c
JIRA: RTOS-219
Modify the way of returning status of programs executed in psh  
Psh recognised terminating program by signal as normal exiting and returned status was set to 0
=> runfile: return correct status after terminating file by signal

metacheck/main.c
The current implementation of the `reverse_bit()` function is inefficient.
For `arm` target, the `rbit` and `rev` instructions were used, which significantly increases the speed of the `reverse_bit()` function.
The performance of the reverse_bit() function can also be improved ( not so significantly ) without using an assembler.
=> metacheck/main.c: improved reverse_bit() function

psh/hm/hm.c, psh/sysexec/sysexec.c
JIRA: RTOS-267
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/536
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/158
https://github.com/phoenix-rtos/plo/pull/215
https://github.com/phoenix-rtos/libphoenix/pull/210
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/348
=> sysexec, hm: Adapt to change in spawnSyspage API

psh/pshapp/pshapp.c
- psh: handle lf/crlf line endings
- Make `pshapp` more flexible
- JIRA: RTOS-281
=> psh: handle lf/crlf line endings

cm4-tool/tool.c
JIRA: RTOS-226
Make utils compatible with fixed threadJoin
- JIRA: RTOS-226
=> utils: fix threadJoin call

psh/touch/touch.c
- psh: touch: switch to open and add strerror
- psh: touch: check a file's existence by utimes()
The current implementation tries to create a file, even if it exists (the case, when fopen returns NULL, because of error)
Printing strerror may be very useful.
- DONE: RTOS-287
=> psh: touch improvements

psh/sysexec/sysexec.c
Change is dedicated mainly to `nil-imxrt1176` target and to those which benefit from `sysexec` in the CLI.
`sysexec` command so far allowed to indicate only the memory map for data (dmap), while it was not possible to indicate the program code memory map (imap), this change introduces the possibility of specifying the code memory map independently of the data memory map (both maps may be default, if not specified, or if specified one will be used).
Additionally this PR changes `sysexec` argument parsing to `getopt()`.
Example use:
```
(psh)% sysexec -m dtcm -M itcm -- flyfrog -F /storage -vvv -l /dev/uart8
```
Will run `flyfrog` with arguments `-F /storage -vvv -l /dev/uart8` using `dtcm` as data memory map and `itcm` as code/text memory map, check of access rights to memory maps (`RWX`) …
=> psh/sysexec: allow use of code memory map

psh/Makefile
PSH_COMMANDS may include external applets, create links for them automatically.
RTOS-377 #done
=> psh: create links also for external aplets

psh/dmesg/dmesg.c
=> psh/dmesg: Fix bad errno check

psh/mount/mount.c
JIRA: RTOS-449
Mount used err instead of errno for its error msg.
=> psh: fix error msg in mount

cm4-tool/tool.c
JIRA: NIL-107
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/368
=> cm4-tool: add options to start core and set vector table offset

_targets/Makefile.sparcv8leon3-gr716, psh/pshapp/pshapp.c
=> add sparcv8leon3-gr716 target

psh/ps/ps.c, psh/top/top.c
=> psh: fix ps/top WAIT column width

cm4-tool/tool.c
=> cm4-tool: Adapt to CM4 driver being moved to the imxrt-multi

psh/psh.c, psh/pshapp/pshapp.c
JIRA: RTOS-499
If swtich from klog already occured do reuse stdin stdout
=> psh: Open `/dev/console` once

psh/Makefile, psh/dd/dd.c
`dd` - The "Swiss army knife".
JIRA: RTOS-399
This change implements copy a file, converting and formatting according to the operands.
supported are: `if`, `of`, `bs`, `count`, `seek`, `skip`, `conv`={`notrunc`, `nocreat`}
Example of use:
```
(psh)% dd if=infile of=outfile bs=1k count=2k
(psh)% dd if=infile2 of=outfile bs=1 count=20 conv=notrunc,nocreat
(psh)% dd if=infile2 of=outfile conv=nocreat count=10 conv=notrunc bs=2
```
=> psh: Implement `dd` command

cm4-tool/tool.c
=> cm4-tool: rx thread optimization

psh/cat/cat.c
Use perror
JIRA: RTOS-584
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/343
=> cat: Fix cat attempting to print directories

psh/ping/ping.c
JIRA: CI-350
Based on:
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/851
=> psh: ping: remove info about min interval

psh/pm/pm.c
- for kernel memory monitoring we need process list (idle process VMEM)
- for total memory used - use meminfo API
JIRA: DTR-443
=> psh: pm: add memory monitoring

psh/echo/echo.c, psh/pshapp/pshapp.c
=> psh: Add stream redirection

psh/dd/dd.c
Adds transfer statistics (bytes, time and speed).
JIRA: RTOS-642
Performance measurements, debugging
=> psh/dd: add transfer statistics

psh/dd/dd.c
Fixes issue where time cannot be estimated due to low clock resolution (mostly on ia32, in example case
`dd count=1 bs=1 < /dev/zero > /dev/null`) and additionally renames the input & output file names when standard in/output was used due to shell stream redirection (`<` stdin, `>` stdout). With this change, to estimate speed, `outtotal` bytes is used instead of (previously) `intotal` bytes. Additionally changed `gettimeofday()` -> `clock_gettime()`.
JIRA: RTOS-642 (fix)
=> psh/dd: fix case when speed cannot be estimated

psd/imx6ull/psd-old.c, psd/imx6ull/psd.c
JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/libphoenix/pull/306
=> Adjust mmap calls to new interface

_targets/Makefile.sparcv8leon3-gr712rc
=> _targets: add sparcv8leon3-gr712rc

psh/ping/ping.c
This change adds hostname resolving functionality to the `ping` command. This makes it more convinient, that user don't have to use `nslookup` to find the hostname before calling the `ping` command (with address returned by `nslookup`), but just use the `ping` command with the `host name`.
`PING host (address): xx data bytes` line is displayed before `host timeout` or other socket errors, to distinguish working resolver.
with this PR:
before this PR:
JIRA: RTOS-687
=> psh/ping: add hostname to IP address resolving

psh/dmesg/dmesg.c
=> dmesg: Add option to disable printing messages to the console

psh/pshapp/pshapp.c
(commit \# 1)
Adaptation of changed code to MISRA
**(commit \# 2)
Change fixes issues mentioned in comment https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/202#discussion_r1405437686**
* if the length of the variable `line` is `< len`, values outside the range of the read line are checked.
* allocating and releasing memory for each line loaded is inefficient.
(commit \# 3)
Introduce ability to comment full lines using `#` at the beginning of line, comments are beneficial for temporarily disabling lines or a little of  narration, eg. (example below)
```bash
:{}:
X /bin/posixsrv
X /bin/psh
```
(commit \# 4)
Change fixes `SCRIPT_MAGIC` checking when a line contains more characters than the defined `SCRIPT_MAGIC` value. e.g. `:{}:123..` with this change is an error.
=> psh: introduce comments in psh script

psh/Makefile, psh/ifconfig/ifconfig.c, psh/psh.c
=> psh: Add ifconfig

psh/pshapp/pshapp.c
Implemented C0 control characters:
- ^A - jump to start of the line;
- ^B - move backward by a char;
- ^E - jump to end of the line;
- ^F - move forward by a char;
- ^K - cut from cursor to the end of line (saved to clipboard);
- ^U - cut from the beginning of line to cursor (saved to clipboard);
- ^W - cut from cursor to the previous whitespace (saved to clipboard);
- ^Y - paste clipboard content at cursor.
Implemented ESC sequences:
- ^[f (Meta/Alt-F) - move forward by a word;
- ^[b (Meta/Alt-B) - move backward by a word;
- ^[d (Meta/Alt-D) - cut from cursor to the next word-boundary (saved
to clipboard);
Implemented CSI/SS3 sequences for Ctrl- and Alt-modified arrow keys:
- Ctrl/Alt+Left - move backward by a word;
- Ctrl/Alt+Right - move forward by a word;
- Ctrl/Alt+Up, Ctrl/Alt+Down …
=> psh: Add fast cursor movement and cut&paste

psh/sysexec/sysexec.c
=> psh/sysexec: Add option to deamonize a new process

psh/top/top.c
- fix line counting (task/threads line was missing, last line was not used)
- fix CMD field overflow
- dynamically adjust to window width & height
DONE: RTOS-474
=> psh: fix top formatting

cm4-tool/tool.c
=> cm4-tool: send path with terminating '\0'

psh/Makefile, psh/route/route.c
Add implementation of `route` (tool to manage internet routes, currently IPv4 only).
```
route [-n] add|del [-net|-host] target [netmask Mask] [gw IP] [metric Numeric] [reject] [[dev] If]
```
The `target` can be provided as regular `IP subnet address` which may require `netmask` to set range (or if not provided the default mask is used), `target` can also be provided using CIDR notation like `ipsubnet/prefixlen` e.g. `1.2.3.0/28` which corresponds to `1.2.3.0 netmask 255.255.255.240`.
If `dev If` is the last option on the command line, the word `dev` may be omitted, as it's the default. Otherwise the order of the route modifiers (`metric`, `netmask`, `gw`, `dev`) doesn't matter, but modifier may appear once.
Tool provides commonly used synonyms for modifiers like:
* `gateway`, abrev. `gw` …
=> psh: implement `route` management tool

_targets/Makefile.riscv64-noelv
=> _targets: add riscv64-noelv target

_targets/Makefile.armv8r52-mps3an536
=> _targets: add armv8r52-mps3an536 target

_targets/Makefile.armv8m33-mcxn94x
JIRA: RTOS-881
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1120
https://github.com/phoenix-rtos/plo/pull/337
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/569
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/132
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/195
https://github.com/phoenix-rtos/libphoenix/pull/371
=> Add MCX N94x target

_targets/Makefile.sparcv8leon-gr740
JIRA: RTOS-883
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
=> _targets: add sparcv8leon-gr740

_targets/Makefile.aarch64a53-zynqmp
=> _targets: add aarch64a53-zynqmp

_targets/Makefile.armv7r5f-zynqmp
=> _targets: add armv7r5f-zynqmp

benchmarks/common/Makefile, benchmarks/common/bench_common.c, benchmarks/common/bench_common.h, benchmarks/dup_close/Makefile, benchmarks/dup_close/main.c, benchmarks/high_load/Makefile, benchmarks/high_load/main.c, benchmarks/jitter/Makefile, benchmarks/jitter/main.c, benchmarks/rhealstone/Makefile, benchmarks/rhealstone/deadlock_break.c, benchmarks/rhealstone/irq_latency.c, benchmarks/rhealstone/msg_latency.c, benchmarks/rhealstone/preemption.c, benchmarks/rhealstone/sem_shuffle.c, benchmarks/rhealstone/task_switch.c
=> add benchmarks

_targets/Makefile.riscv64-gr765, _targets/Makefile.riscv64-grfpga
=> _targets: rename noelv to gr765
